stages:
  - dependencies
  - pipeline
  - test

image: python:3.8.6

install-dependencies:
    stage: dependencies
    script: python -m pip install --upgrade pip setuptools whee
            pip install pylint --upgrade

test-code-job:
  stage: test
  script:
    - echo "Ejecutamos los tests"
    - python test.py

analize-pslint:
    stage: pipeline
    script: pylint test.py